### ISSUE TITLE
Removal of aai_index module

### ISSUE THREAD

**Issue by nick-youngblut** [cruizperez/FastAAI#12]
I recently updated FastAAI, and now I get the following error when running `fastaai aai_index`:

```
 I couldn't find the module you specified. Please select one of the following modules:
```

So, it appears that the UI was dramatically changed, but I can't find a changelog or release notes stating this. Which is the last pypi release to contain aai_index? 

Also, it appears that your docs still include aai_index:

```
	If you wish to query multiple genomes against themselves in all vs. all AAI search, use aai_index instead.
	If you wish to query multiple genomes against multiple targets, use multi_query instead.
```

...but aai_index was commented-out a few lines lower in the code:

```
		#print("    multi_query  |" + " Create a query DB and a target DB, then calculate query vs. target AAI")
		#print("    aai_index    |" + " Create a database from multiple genomes and do an all vs. all AAI index of the genomes")
```

**Comment by KGerhardt** [comment]
Hello Nick,

I had removed some of the modules while I was performing a significant overhaul of the code that changed multiple inputs in some of the more basic modules of FastAAI. The aai_index command is equivalent to sequentially running build_db and db_query on the resulting database, if you would like to replicate the behavior of aai_index right away.

Release 0.1.9 should be the last version that had the aai_index command. As a warning, that version uses a different method of representing kmers when compared to the current version and databases built with the old code are not compatible with the revision. I plan to release a conversion script, but it isn't a high priority since we don't have a lot of users, yet.

I can, however, go back in and add the aai_index and multi_query functions I had removed. I'll have this done by the end of the weekend.

**Comment by nick-youngblut** [comment]
Thanks @KGerhardt for the info (and the warning)! I'm fine with closing this issue, unless you want to keep it open until after you re-add the `aai_index` and `multi_query` functions back

**Comment by KGerhardt** [comment]
aai_index and multi_query have been re-added.

I've added a few modules that are not listed in the selection menus as well. They're intended for my lab's internal use, but are functional for those who want to use them, too. They are "miga_preproc" and "miga_db_from_crystals."

The miga_preproc function runs the first half of a database build and outputs files with the best-matching SCP names, accessions, and protein sequences in addition to the protein and HMM files normally produced from a set of genomes in an additional "crystals" subdirectory of the output. The miga_db_from_crystals function rapidly builds a database from these already mostly preprocessed files. 

If you think you're going to reuse genomes for multiple databases frequently, it may be better to use the miga_preproc module instead of the standard build. I plan to incorporate this behavior into the normal build function with a --crystalize flag at a later date.
